const MessageTag = {
  ALL_REQ: 'All fields are required',
  ValidEmail: 'Please enter a valid email',
  WelcomeMsg: 'Welcome to Virtuevise Portal.',
  PasswordWrong: 'Password incorrect.',
  NotFoundEmail: 'User Not Found.',
  EXIST_GTC: 'Category already exists.',
  GTC_NOT: 'Category Not found.',
  GTC_UPDATE: 'Category updated successfully.',
  GTC_ADD: 'Global Type Category Added Successfully.',
  GTC_DELETE: 'Category deleted successfully.',
  GTC_LIST: 'GLobal Type Category List.',
  GLOBALTYPE_ADD: 'Global Type Added Successfully.',
  GLOBALTYPE_NOT_FOUND: 'Global type not found with this category.',
  GLOBALTYPE_EXIST: 'Global type already exists.',
  GLOBALTYPE_NOT_EXIST: 'Global type not found.',
  GLOBALTYPE_DELETE: 'Global type deleted successfully.',
  GLOBALTYPE_UPDATE: 'Global type updated successfully.',
  USER_EXIST: 'User Already exists.',
  USER_ADDED: 'User Added Successfully.',
  ERROR_OCCURRED: 'Some error occurred while creating record.',
  CONTENT_NOT_FOUND: 'Content can not be empty.',
  LEAVE_EXIST: 'Leave already applied for this date.',
  LEAVE_MARK: 'Leave Marked.',
  LEAVE_UPDATED: 'Leave Updated.',
  EVENT_EXIST: 'Event already added for this date.',
  EVENT_MARKED: 'Event Added.',
  EVENT_UPDATED: 'Event Updated.',
  EMAIL_EXISTS: 'Email already exists.',
  EMPLOYEE_ID_EXISTS: 'Employee ID already exists.',
  ATTENDANCE_NOT_FOUND: "Data doesn't exist.",
  INVALID_TOKEN: 'Invalid token.',
  EMAIL_NOT_FOUND: 'Email not found.',
}

module.exports = MessageTag
